# Use this docker-compose file to host the site locally
version: '3.7'
services:
  nginx:
    container_name: nginx
    build: docker/nginx-container
    image: milken/nginx-dev
    expose:
      - 80
      - 9222
    depends_on:
      - php
      - mysql
    links:
      - php
      - mysql
    volumes:
      - ".:/var/www"
    ports:
      - "8080:80"
      - "9222:9222"
    env_file:
      - .env

  php:
    container_name: php
    build: docker/php-container
    image: milken/php-dev
    expose:
      - '9000'
      - '4444'
    links:
      - solr
    volumes:
      - ".:/var/www"
      - "$HOME/.ssh:/root/.ssh"
    env_file:
      - .env

  mysql:
    container_name: mysql
    build: docker/mysql-container
    image: milken/mysql-dev
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - 'db:/var/lib/mysql'
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis
    expose:
      - '6379'

  solr:
    container_name: solr
    image: milken/solr-dev
    build: docker/solr-container
    environment:
      - JAVA_HOME=/usr/local/openjdk-11
    env_file:
      - .env
    expose:
      - "8983"
    ports:
      - "8983:8983"

volumes:
  web: {}
  db: {}
