module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  block: 0
  block_content: 0
  bootstrap_library: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_filter: 0
  config_split: 0
  content_sync: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  default_content: 0
  default_content_extra: 0
  delete_all: 0
  diff: 0
  ds: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  hal: 0
  image: 0
  imagick: 0
  inline_entity_form: 0
  jsonapi: 0
  kint: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  markdown: 0
  media: 0
  media_entity_browser: 0
  media_entity_browser_media_library: 0
  media_library: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rdf: 0
  react_component: 0
  redis: 0
  responsive_image: 0
  search_api: 0
  search_api_solr: 0
  serialization: 0
  settings_tray: 0
  svg_image_field: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  webpack: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  milken_migrate: 30
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
  bootstrap_barrio: 0
  adminimal_theme: 0
  milken: 0
  bartik: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
